### ISSUE TITLE
ClassNotFoundException: com.jcraft.jsch.jce.Random

### ISSUE THREAD

**Issue by flyrev** [dacr/jassh#33]
> java.lang.ClassNotFoundException: com.jcraft.jsch.jce.Random [class com.jcraft.jsch.JSchException] 
> com.jcraft.jsch.JSchException: java.lang.ClassNotFoundException: com.jcraft.jsch.jce.Random
> 	at com.jcraft.jsch.Session.connect(Session.java:198) ~[project.jar:na]
> 	at fr.janalyse.ssh.SSH.fr$janalyse$ssh$SSH$$buildSession(SSH.scala:310) ~[project.jar:na]
> 	at fr.janalyse.ssh.SSH.<init>(SSH.scala:266) ~[project.jar:na]
> 	at fr.janalyse.ssh.SSH$.once(SSH.scala:57) ~[project.jar:na]

In my pom.xml I have

        <dependency>
            <groupId>fr.janalyse</groupId>
            <artifactId>janalyse-ssh_2.11</artifactId>
            <version>0.10.0</version>
        </dependency>

Is there some extra dependency I should include to get this to work?

**Comment by flyrev** [comment]
For those experiencing this: ensure that your build tool does not strip the JAR of necessary classes.
