### ISSUE TITLE
java.lang.ClassNotFoundException: com.jcraft.jsch.DHGEX256

### ISSUE THREAD

**Issue by flyrev** [dacr/jassh#34]
I now have these additional dependencies added to my pom.xml:
```
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.jsch</artifactId>
            <version>0.1.54_1</version>
        </dependency>

        <dependency>
            <groupId>net.sourceforge.getl</groupId>
            <artifactId>getl</artifactId>
            <version>1.2.11</version>
        </dependency>
```

Now, I get

com.jcraft.jsch.JSchException: java.lang.ClassNotFoundException: com.jcraft.jsch.DHGEX256
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:605) ~[project.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:320) ~[project.jar:na]
	at fr.janalyse.ssh.SSH.fr$janalyse$ssh$SSH$$buildSession(SSH.scala:310) ~[project.jar:na]
	at fr.janalyse.ssh.SSH.<init>(SSH.scala:266) ~[project.jar:na]
	at fr.janalyse.ssh.SSH$.once(SSH.scala:57) ~[project.jar:na]

Any ideas what I need to add?

**Comment by dacr** [comment]
strange this error, could give me more information about the usage context, used JVM family (hotspot ?) and release (8u??, 9u??), ssh server release, ...

**Comment by flyrev** [comment]
For those experiencing this: ensure that your build tool does not strip the JAR of necessary classes.
